# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [1]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np 

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [2]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [3]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility

#YOUR CODE HERE
myarray=np.random.randint(0,100,(5,3))
# Print out the array
print(myarray)

[[37 12 72]
 [ 9 75  5]
 [79 64 16]
 [ 1 76 71]
 [ 6 25 50]]


### 1.2 Solution - Run the following cell to check your answer.

In [4]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [5]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]
p1=703*170/(55)**2
print(p1)
p2=703*180/(120)**2
print(p2)
p3=[p1,p2]
bmi=np.array(p3)
print(bmi)


39.50743801652892
8.7875
[39.50743802  8.7875    ]


### 1.3 Solution: Run the following cell to check your answer.

In [6]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [49]:
def my_func(m1,m2,r,c):
    return np.random.randint(m1,m2,(r,c))

r = int(input(" Enter number of rows"))
c = int(input(" Enter number of column"))
random_array = my_func(1,30,r,c)
t=random_array
print(t.dtype)
changed = t.astype(np.float64)
print(changed.dtype)
print ("my array\n", random_array)


int32
float64
my array
 [[12  4 11  4  1]
 [13  6 11 12 11]
 [18 19  2 23  3]
 [15 15 18 13  4]
 [15 16 23 20 10]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [8]:
# 1. Return the first row:
print(random_array[0])


[21  6 19 21 12 29]


In [9]:
# 2. Return the last column
print(random_array[:,-1])

[29 24 23 26 25  9]


In [10]:
# 3. Return the third column values from the 4th and 5th rows

print(random_array[4:,3:4])

[[18]
 [11]]


In [11]:
# 4. Multiply every value in the array by 2
random_array=random_array * 2
print(random_array)

[[42 12 38 42 24 58]
 [22 58 30 38 10 48]
 [48 20 36 48  2 46]
 [28 20 20 16 46 52]
 [ 4  2 58 36 18 50]
 [28 40 32 22 52 18]]


In [12]:
# 5. Divide every value by 3
print(random_array/3)

[[14.          4.         12.66666667 14.          8.         19.33333333]
 [ 7.33333333 19.33333333 10.         12.66666667  3.33333333 16.        ]
 [16.          6.66666667 12.         16.          0.66666667 15.33333333]
 [ 9.33333333  6.66666667  6.66666667  5.33333333 15.33333333 17.33333333]
 [ 1.33333333  0.66666667 19.33333333 12.          6.         16.66666667]
 [ 9.33333333 13.33333333 10.66666667  7.33333333 17.33333333  6.        ]]


In [13]:
# 6. Increase the values in the first row by 12
print(random_array[0]+12)

[54 24 50 54 36 70]


In [14]:
# 7. Calculate the mean of the first column
print(int(np.mean(random_array[:,0])))

28


In [36]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
myarray = np.sort(random_array, axis=None)
myarray = myarray[2:]
print(np.median(myarray))


36.0


In [16]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array
new_array=np.random.randint(0,100,(5,5))
print(new_array)
print(np.std(new_array[:3,:]))

[[40 15 72 22 43]
 [82 75  7 34 49]
 [95 75 85 47 63]
 [31 90 20 37 39]
 [67  4 42 51 38]]
26.147785119712655


In [22]:
# 10. Return values in the second column greater than 25
t2_array=new_array[: , 1] >25
print(new_array[t2_array])

[[82 75  7 34 49]
 [95 75 85 47 63]
 [31 90 20 37 39]]


In [18]:
# 11. Return values < 40 in the array
t1_array=new_array[:,:] >40
print(new_array[t1_array])

[72 43 82 75 49 95 75 85 47 63 90 67 42 51]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [19]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[33 58 67]
 [69 88 68]
 [46 70 95]
 [83 31 66]
 [80 52 76]]


1. The first row:  [33 58 67]


2. The last column:  [67 68 95 66 76]


3. The 3rd column, 4th & 5th rows:  [66 76]


4. Multiply by 2: 
 [[ 66 116 134]
 [138 176 136]
 [ 92 140 190]
 [166  62 132]
 [160 104 152]]


5. Divide by 3: 
 [[11.         19.33333333 22.33333333]
 [23.         29.33333333 22.66666667]
 [15.33333333 23.33333333 31.66666667]
 [27.66666667 10.33333333 22.        ]
 [26.66666667 17.33333333 25.33333333]]


6. Add 12 to the first row: 
 [45 70 79]


7. The mean of the 1st column:  62.2


8. The median after removing the 2 smallest values:  69.0


9. The standard deviation is:  27.027192525352483


10. All values in 2nd column > 25: 
 [[63 79 49]
 [39 46  8]]


11. All values < 40: 
 [ 4 39  8 15  8 17 22]
